#!/usr/bin/env bash

# Install nginx and ensure it's running
apt-get update
apt-get -y install nginx

# Remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default

# Create a new nginx configuration file
cat > /etc/nginx/sites-available/default <<- EOM
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\.ht {
        deny all;
    }
}
EOM

# Create a new index.html file in the nginx root directory
cat > /var/www/html/index.html <<- EOM
<html>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOM

# Reload the nginx configuration to apply the changes
nginx -s reload
