#!/usr/bin/env bash
# Bash script to fix the default server port access issue
rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
